name: Build and deploy Node.js app to Azure Web App - demoShopping

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20 for frontend
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # FRONTEND
      - name: Install deps (frontend)
        run: npm ci
        working-directory: ./frontend

      - name: Build (frontend)
        run: npm run build
        working-directory: ./frontend

      # Copie le build du front dans le dossier statique du backend
      # Adapte "public" Ã  ce que ton backend sert (public|dist|static)
      - name: Prepare backend static assets
        run: |
          mkdir -p backend/public
          rm -rf backend/public/*
          cp -r frontend/dist/* backend/public/

      # BACKEND
      - name: Install deps (backend)
        run: npm ci
        working-directory: ./backend

      - name: Build (backend) # supprime si pas de script build
        run: npm run build --if-present
        working-directory: ./backend

      # On uploade UNIQUEMENT le backend (qui contient maintenant les assets du front)
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-backend
          path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-backend
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_095B1D26FE1F4D58B8FFE21AE40EDEB4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0B5A200ACC8241BE81F4C9F1AB52448C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0778DDBDD41148838A58DB80D6806018 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'demoShopping'
          slot-name: 'Production'
          package: .

          
